
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: muxin-netty
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/muxin-dev?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.coolron.muxin.domain
  mapper-locations: classpath:mapping/muxin/*.xml
# 通用 mapper 配置
mapper:
  # mappers: com.coolron.muxin.util.MyMapper
  not-empty: false
  identity: MYSQL

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.1.105:22122
    - 192.168.1.106:22122




